"""add scan indexes

Revision ID: 23ee59aaf63c
Revises: 1d3aaaec1943
Create Date: 2026-03-07 16:29:26.866266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ee59aaf63c'
down_revision = '1d3aaaec1943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pii_scans', schema=None) as batch_op:
        batch_op.create_index('idx_scan_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_scans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pii_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pii_scans_user_id'))
        batch_op.drop_index(batch_op.f('ix_pii_scans_created_at'))
        batch_op.drop_index('idx_scan_user_created')

    # ### end Alembic commands ###
