"""add scan status

Revision ID: e33c0ae9d9ce
Revises: 23ee59aaf63c
Create Date: 2026-03-07 17:42:39.627520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33c0ae9d9ce'
down_revision = '23ee59aaf63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pii_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pii_scans', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
